org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Fabric Properties
minecraft_version=1.21.11
loader_version=0.19.2
loom_version=1.16-SNAPSHOT

# Mod Properties
mod_version=1.0.0
maven_group=com.zyphron.memoryleakfix
mod_id=memoryleakfix

# Dependencies
fabric_api_version=0.147.0+1.21.11
